services:
  - type: web
    name: tyusha-server
    env: node
    plan: free
    region: frankfurt
    buildCommand: |
      rm -rf node_modules package-lock.json
      npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGO_URI
        value: <ТВОЯ_РЕАЛЬНА_MONGO_URI>
      - key: JWT_SECRET
        value: <ТВОЙ_SECRET>
      - key: PORT
        value: 5000
